//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlAgilityPackTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int ShowId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Occupation { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public DateTime? PublishedDate { set; get; }
        public string ChildUrl { get; set; }
        public Nullable<int> IsNew { get; set; }
    }
}
