//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlAgilityPackTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowDetail
    {
        public int ShowDetailId { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public int ShowId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
